Web 4344 event machine behavior dependency injection
tarfin-labs/event-machine pull request #70
Opened 2023-12-05 19:18 UTC by deligoez

2023-12-06 06:12 UTC, aydinfatih requested changes

2023-12-06 06:12 UTC, aydinfatih commented on tests/ActionTest.php
> +        public function definition(): Closure
Burası eski kalmış olabilir mi?

2023-12-06 06:12 UTC, aydinfatih commented on tests/ActionTest.php
> +    $result = $multipleWithItselfAction->definition()(
Burası eski kalmış olabilir mi? definition metotu kaldırılmıştı

2024-01-11 22:15 UTC, deligoez commented on tests/ActionTest.php
> +    $result = $multipleWithItselfAction->definition()(
evet, duzelttim bu testi

2024-01-12 05:46 UTC, aydinfatih approved these changes

2024-01-12 07:07 UTC, merged