Add support to set machines in a model using `machines()` method.
tarfin-labs/event-machine pull request #82
Opened 2024-08-05 14:05 UTC by tkaratug

This PR adds support to set machines via `machines()` method in a model in order to use expressions.

2024-08-07 06:58 UTC, aydinfatih requested changes

2024-08-07 06:58 UTC, aydinfatih commented on src/Traits/HasMachines.php
> +                method_exists($this, 'machines') && array_key_exists($key, $this->machines()) => $this->machines()[$key],
Machines metotunu 2 kere çalıştırmışız. 1 kere çalışacak şekilde güncellenebilir mi?

2024-08-08 08:56 UTC, tkaratug commented on src/Traits/HasMachines.php
> +                method_exists($this, 'machines') && array_key_exists($key, $this->machines()) => $this->machines()[$key],
match statement'ı normal if'e çevirmek lazım. sadece array return ettiği için çok problem değil bence.

2024-08-08 09:01 UTC, aydinfatih commented on src/Traits/HasMachines.php
> +                method_exists($this, 'machines') && array_key_exists($key, $this->machines()) => $this->machines()[$key],
Artık metotun içinde sistemi yoracak veritabanı bağlantısı, dosya okuma vs  işlerde yapılabilir. bu işlerin tekrarlı çalışması performans kaybına neden olabilir diye düşünüyorum. (Bizim case için değilde paketin genel kullanımına yönelik)

2024-08-08 09:06 UTC, tkaratug commented on src/Traits/HasMachines.php
> +                method_exists($this, 'machines') && array_key_exists($key, $this->machines()) => $this->machines()[$key],
Mantıklı, if'e çevrildi.

2024-08-08 09:08 UTC, aydinfatih requested changes

2024-08-08 09:08 UTC, aydinfatih commented on src/Traits/HasMachines.php
> +            if (property_exists($this, 'machines')) {
else if olabilir. Hem metot hem property tanımlanırsa 2 ifte çalışacaktır.

2024-08-08 09:28 UTC, aydinfatih approved these changes

2024-08-12 13:24 UTC, tkaratug commented
Hi Team,

I’m closing this PR because Laravel 11 introduced the ability to perform custom casting directly within the `casts()` method. 

This new feature makes the changes proposed in this PR redundant, as the same functionality can now be achieved in a more integrated way within the framework.

2024-09-04 13:55 UTC, merged