Able to Reset All Fakes
tarfin-labs/event-machine pull request #86
Opened 2024-11-05 17:31 UTC by deligoez

The resetAllFakes method within the Fakeable trait is intended to clear all fake instances from the application container. However, it appears to be leaving some bindings intact, leading to failures in tests expecting the container to be fully reset. This behavior is likely due to the incomplete handling of bindings and instances in the reset process, impacting App::bind, App::has, and App::forgetInstance.

2024-11-06 06:02 UTC, tkaratug approved these changes

2024-11-06 09:20 UTC, aydinfatih requested changes

2024-11-06 14:53 UTC, deligoez commented on src/Traits/Fakeable.php
> +        Mockery::resetContainer();
bu cok yerine bir cekince, zor oldu ama, duzelttim

2024-11-06 14:54 UTC, deligoez commented on src/Facades/EventMachine.php
> +class EventMachine extends Facade
bu degisikligi zaten yapmistim neden PR'ya yansimamis anlamadim, asagidaki nottaki degisiklikleri gonderince, composer.json'daki degisiklikler gorunmeye basladi bende.

2024-11-06 14:59 UTC, aydinfatih commented on src/Traits/Fakeable.php
> +        Mockery::resetContainer();
Şu anda nasıl yapıyor abi tam anlayamadım

2024-11-06 17:54 UTC, deligoez commented on src/Traits/Fakeable.php
> +        Mockery::resetContainer();
mockery'de 2 turlu durum var, mock'un instance'i ve bu mock'a ait expectation'lar.

mock'u teardown yapinca, daha once tanimlanan expectation'lar karsilanmamis oluyor ve testler gecmiyor.

cleanupMockeryExpectations() metodunda $mock'a her bir metodu icin tanimlanmis expectation'lara (burada sadece __invoke() ) yeni ve bos ExpectationDirector atiyoruz, diger bir deyisle bos beklenti atiyoruz.

2024-11-07 06:24 UTC, aydinfatih commented on src/Traits/Fakeable.php
> +        Mockery::resetContainer();
Açıklama için teşekkürler

2024-11-07 06:25 UTC, aydinfatih approved these changes

2024-11-07 15:01 UTC, merged